kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: test-analysis-for-canary
spec:
  args:
    - name: start-time
    - name: experiment-hash
  metrics:
    - name: test-analysis-for-canary
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: demoappforcanary
          user: admin
          baselineStartTime: "{{args.start-time}}"
          canaryStartTime: "{{args.start-time}}"
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: demoservice
            gateName: demo-gate
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.experiment-hash}}.*baseline.*" 
            canaryLogScope: ".*{{args.experiment-hash}}.*canary.*"
            metricScopeVariables: "namespace_key,pod_key"
            baselineMetricScope: "argocd,.*{{args.experiment-hash}}.*baseline.*"
            canaryMetricScope: "argocd,.*{{args.experiment-hash}}.*canary.*"
