apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: oes-analysis-isd
spec:
  args:
  - name: start-time
  metrics:
    - name: oes-analysis-isd
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          application: dempappforcanary
          user: admin
          baselineStartTime: "{{args.start-time}}"
          canaryStartTime: "{{args.start-time}}"
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
